from fastapi import APIRouter

from backend.models.schemas import ChatRequest

router = APIRouter()


@router.post("/chat")
async def chat(payload: ChatRequest) -> dict[str, object]:
    return {
        "response": "This is a demo response generated by the agent scaffold.",
        "conversation_id": payload.conversation_id or "demo-conversation",
        "recommended_schemes": [],
        "checklist": [],
    }
